CREATE TABLE IF NOT EXISTS game (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  phase TEXT NOT NULL DEFAULT 'open',
  killer_id TEXT DEFAULT NULL,
  clean_clue INTEGER NOT NULL DEFAULT 0,
  judged INTEGER NOT NULL DEFAULT 0,
  revealed_at TIMESTAMPTZ DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS guests (
  id TEXT PRIMARY KEY,
  pin_hash TEXT NOT NULL,
  accused TEXT,
  motive TEXT DEFAULT '',
  clue TEXT DEFAULT '',
  primary_done INTEGER NOT NULL DEFAULT 0,
  bonus_done INTEGER NOT NULL DEFAULT 0,
  submitted INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS judgements (
  id TEXT PRIMARY KEY,
  motive_ok INTEGER NOT NULL DEFAULT 0,
  clue_ok INTEGER NOT NULL DEFAULT 0,
  primary_ok INTEGER NOT NULL DEFAULT 0,
  bonus_ok INTEGER NOT NULL DEFAULT 0
);
